### ISSUE TITLE
"Reading older preferences" error stops the game from booting.

### ISSUE THREAD

**Issue by Xenomorph-III** [Aleph-One-Marathon/alephone#247] opened 2021-02-13 10:25 UTC
### Describe the bug

No matter the scenario used, attempting to boot Aleph One on Fedora 33 at least ends with a message saying,
```
while initializing preferences (preferences.cpp:2951)
  Reading older preferences of version 20200803. Preferences will be upgraded to version 20200904 when saved. (/home/admin/AlephOneData/Infinity/Scripts/Default Preferences.xml) (preferences.cpp:3031)
Unhandled exception: conversion of type "PKc" to data failed (shell.cpp:363)
```

Deleting the `~/.alephone ` folder or going into the scenario folder and deleting the preferences folder doesn't work at all.

### Steps To Reproduce

Install Aleph One on Fedora 33 using the Linux install instructions.
Boot up Aleph One with any scenario.
Observe error.

### Expected behavior

The scenario starts up and allows me to play the game.

### Versions and configuration

OS Version: Fedora Linux 33 KDE Spin
Aleph One version: 13.1 Stable

**Comment by treellama** [comment] 2021-02-13 12:06
Duplicate of #246

**Closed by treellama** 2021-02-13 12:06 UTC
