### ISSUE TITLE
In singleplayer, after exactly 15 level transitions, the game freezes

### ISSUE THREAD

**Issue by SolraBizna** [Aleph-One-Marathon/alephone#55] opened 2016-09-06 23:16 UTC
This bug is present in the most recent stable release as well as recent git. It can be bypassed by attaching with a debugger, manually reducing heartbeat_count by 15, and (if necessary) manually clearing the action queues.

There is a fix for this in my 60fps branch. I would have reported it when I discovered it then, but I assumed it was a 60fps-specific bug. (I also wrongly assumed it would be avoided if the game loop ran efficiently enough to occasionally sleep.) https://github.com/SolraBizna/alephone/commit/5abb99c60a16dd32f02df7819be47cf947220b66

I don't think it's a coincidence that 15 is exactly MAXIMUM_TIME_DIFFERENCE.

**Comment by Hopper262** [comment] 2016-09-07 02:27
Closing as duplicate of #53.

**Closed by Hopper262** 2016-09-07 02:27 UTC

**Comment by SolraBizna** [comment] 2016-09-07 21:05
It's really freaky that this went unnoticed for so long, then generated two issues in two days. :|
