### ISSUE TITLE
1.3b3 Texture flickering on Marathon EVIL map

### ISSUE THREAD

**Issue by Captain-Fwiffo** [Aleph-One-Marathon/alephone#188] opened 2020-05-20 06:35 UTC
I created a helpful video to show what the bug is exactly. It is an issue with the renderer. The map is "All dressed up, and no place to go."

https://www.youtube.com/watch?v=0Q_e86zdfyo

The bug is not present with the Classic renderer. Only present in OpenGL.

I went ahead and tested it in previous versions. The flickering is not present in OpenGL (classic) or the Classic renderer in 1.2.1, but it is present in OpenGL (shader) in 1.2.1. 

In 1.3b2, it is present exactly the same in the OpenGL renderer, but not in Classic renderer.

If this Github issue is in any way unsatisfactory to you, please direct all concerns to wrkncacnter, who advised me that this was a bug with the renderer and encouraged me to file a report. I cheated more than a college student in an online exam while getting to that location in the video I recorded.

I am on Windows. Same preferences and specs as the last issue.

**Comment by aaronfreed** [comment] 2020-05-22 01:23
There are issues with this in Marathon 2 as well, specifically in the level “What About Bob?” I would’ve focused on this a bit more if I’d been thinking about it, but you can still briefly see it here: https://youtu.be/qwySYINhfyg?t=35

I think there’s a similar issue in “Hang Brain” in Infinity, but I can’t remember where it was and don’t currently have time to look through a whole film of it to find out. If you’re curious, I have a few films of it starting here https://www.youtube.com/watch?v=svDTqZ-HoDc&list=PLoysJW6pXQ6lrBGIwx-GONRw8jmND9plV – I’m sure it’ll show up in at least one of them.

I believe the issue is that the renderer doesn’t know what to do when a split polygon has a ceiling higher than its floor, so it tries displaying both textures. I presume a fix would be just to handle this however the classic renderer handles it (which is presumably based on the ceiling height of the split polygon, judging from how ”What About Bob?” looks in the classic renderer).

This has been around since at least 1.2.1 (which most of these films were rendered in), and I should’ve reported it a lot sooner, but I just didn’t remember it until Fwiffo made this issue.

**Comment by TrajansRow** [comment] 2020-05-22 02:41
I think what you are seeing here is a common artifact in 3D graphics called Z-Fighting. It happens when the GPU is trying to draw overlapping surfaces using depth-testing, but can’t tell which is nearer to the viewer. That can happen when geometry is very close together, or if there is insufficient precision at that region of the depth buffer.

This was not so much of an issue in the older OpenGL renderer, because Z-buffering could be turned off. However in the shader renderer, it is required to be enabled. Normal 3D games largely avoid this problem by disallowing coplanar geometry, or by adding in an artificial depth bias in known cases (such as for decals).

Unfortunately, I can’t think of a really easy way to fix this without changing the map. There might be something we could do with some polygon offset trickery, but I will have to think about that.

**Comment by aaronfreed** [comment] 2020-05-26 21:04
I’ve been thinking about this. Do the classic renderer and software mode always just default to using the ceiling height as a split point in cases like this? I was assuming that was the case, but maybe it’s more complicated than that. But if it really is that simple, then if there’s a way to make the shader duplicate that behaviour when the floor height exceeds the ceiling height, that would probably be the simplest fix. It’s *probably* just a conditional that can be added somewhere that would only take precedence in the rare cases where such a polygon occurs. Is there something else I’m missing that would prevent this from working as a fix for this issue?

**Comment by treellama** [comment] 2021-03-13 14:12
The problem on "What About Bob" is only severe when the "3D Perspective" checkbox is enabled and the view is tilted. I am guessing this is because the clipping windows are calculated with the view perpendicular to the ground, so OpenGL Classic and non-3D perspective shader would Y-clip most of the overlap.

Updating the vis-tree to account for the player pitch might improve this, but it's not a high priority for me.

There's still a tiny amount of Z-fighting even with 3D perspective off, but that goes back to TrajanRow's point.

**Closed** 2023-08-22 02:22 UTC
