### ISSUE TITLE
Deathless session glitch

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#78] opened 2017-08-11 10:25 UTC
If you play enough stages without dying in row the game crashes. This has happened to multiple people, the speedruns have an intentional death in them so they avoid the crash.

**Comment by Hopper262** [comment] 2017-08-11 15:52
This is a duplicate of #53 and is fixed in the code. The fix has not yet made it into a stable release.

**Closed by Hopper262** 2017-08-11 15:52 UTC
