### ISSUE TITLE
Misaligned/ stretched terminal image (Marathon Infinity)

### ISSUE THREAD

**Issue by rzhxiii** [Aleph-One-Marathon/alephone#417] opened 2023-06-01 07:58 UTC
One of the terminals from Eat the Path has its image too far to the right, to the point where it displays partially under the terminal text.
I am currently playing under OpenGL at 960x720 with the original HUD and both HUD and Terminal size are set to largest, but this seems to be a general issue with this terminal since it also happens with the software renderer and with custom HUDs, such as the XBLA one or FloatingX (I don't know if any other terminals have this issue, but I haven't checked all of them).
![misaligned](https://github.com/Aleph-One-Marathon/alephone/assets/82729328/7a9071ce-bbc7-4bd9-b982-7a88b4140a4d)

**Comment by Kolfering** [comment] 2023-06-10 20:57
I could reproduce this issue.
I splitted the map with atque then merged it back without changing anything and it fixed the problem.
I didn't investigate further the cause but I guess there is probably some weird characters there leading to this misinterpretation?

**Closed** 2023-09-10 02:43 UTC
