### ISSUE TITLE
Allow option for Nearest-Neighbor scaling of non-native resolutions

### ISSUE THREAD

**Issue by OpenRift412** [Aleph-One-Marathon/alephone#363] opened 2022-07-12 17:55 UTC
Due to some [recent discoveres](https://github.com/Aleph-One-Marathon/alephone/issues/342#issuecomment-1177580167) with Marathon 1, I would like to make a suggestion that when the game is running in a non-native resolution, have it use nearest-neighbor scaling when playing in a resolution that does not match the desktop resolution. This would mostly be for a more authentic retro feel.

**Comment by treellama** [comment] 2022-07-15 14:29
Duplicate of #341

**Closed** 2022-07-15 14:30 UTC
