### ISSUE TITLE
Sprites showing through solid surfaces

### ISSUE THREAD

**Issue by Q3BFG10K** [Aleph-One-Marathon/alephone#271] opened 2021-04-15 11:03 UTC
Load the Marathon 2 save and you'll see the dead monster sprite showing through the wall. If you walk forward it'll disappear.

[1618415216.zip](https://github.com/Aleph-One-Marathon/alephone/files/6317337/1618415216.zip)

**Comment by treellama** [comment] 2021-04-15 11:52
Possibly a duplicate of #198 or #206

**Comment by LidMop** [comment] 2021-04-15 19:53
Yup, this is #198. I'm still working on a large overhaul to fix all of these sprite issues.

**Closed** 2021-04-15 20:05 UTC
