### ISSUE TITLE
Assertion failed! (Windows 10)

### ISSUE THREAD

**Issue by Corruptinator** [Aleph-One-Marathon/alephone#59] opened 2016-12-03 04:57 UTC
I wanted to see how the original Marathon runs on Windows 10 but as soon as I hit Start Game, it crashed and gave me a Microsoft Visual C++ Runtime Library Error:

Assertion failed!

Program:...
File: shapes.cpp
Line: 2043

Expression: Bitmap

I have no idea on what is causing this to happen, but just wanted to give a heads up of a crash.

I am using a Windows 10 Anniversary Version OS 64-Bit.

**Comment by Ao1Pointblank** [comment] 2023-05-28 20:54
for me this was caused by a plugin not meant for marathon 1 (it was brutal marathon for 2/infinity)

**Comment by Corruptinator** [comment] 2023-06-06 06:19
Very interesting. @Ao1Pointblank.

**Comment by Ao1Pointblank** [comment] 2023-06-06 22:45
yeah im just a few years late. i dont even know if that plugin was released in 2016. it could be another plugin though. aleph one is usually very stable with default settings. the only other issue i have had is when copying preference files between scenarios and encountering incompatible settings, but that has another way of manifesting the errors.

**Closed** 2023-09-10 02:08 UTC
